### ISSUE TITLE
Reference Tree tab throws NPE.

### ISSUE THREAD

**Issue by ykubota** [HeapStats/HeapStatsFXAnalyzer#13]
After @4f79016, Reference Tree tab throws NPE as below.

 - Select SnapShot Data tab.
  - Do not select any objects on table.
 - Select Reference Tree tab.

![image](https://cloud.githubusercontent.com/assets/489607/9788002/160b8716-5802-11e5-8403-38cc0f947665.png)

```
java.lang.NullPointerException
	at jp.co.ntt.oss.heapstats.plugin.builtin.snapshot.tabs.ReferenceCell.<init>(ReferenceCell.java:76)
	at jp.co.ntt.oss.heapstats.plugin.builtin.snapshot.tabs.RefTreeController.initializeSwingNode(RefTreeController.java:114)
	at jp.co.ntt.oss.heapstats.plugin.builtin.snapshot.tabs.RefTreeController.lambda$buildTab$58(RefTreeController.java:99)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ykubota** [comment]
Simply change.

![image](https://cloud.githubusercontent.com/assets/489607/9807170/4278d33e-588a-11e5-906b-2d8e1a16b653.png)

**Comment by YaSuenag** [comment]
Looks good!

**Comment by ykubota** [comment]
Merged.
